# Generated by Django 5.1.4 on 2024-12-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='version',
            new_name='v',
        ),
    ]
