# Generated by Django 5.1.4 on 2024-12-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_rename_version_book_v'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='v',
            new_name='version',
        ),
    ]
